### PR TITLE
Tezos (XTZ) SDK added

### PR DESCRIPTION
**Pull request by ellingtonsu**
Tezos (XTZ) SDK and its coin-tester app are added.
----

*Checklist:*

- README.md includes:
  - [ O ] The details of signing data and transaction data, this includes parameters.
  - [ X ] Official docs or white paper.
  - [ O ] Website or api can query assets and broadcast transaction.

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by skchang0710** [comment]
Hi @ellingtonsu, thank you for your support on the coin integration. I've tested your code and it works well till the signTransaction.
Screen Shot 2022-03-09 at 11 43 35 AM

**Comment by ellingtonsu** [comment]
> Hi @ellingtonsu, thank you for your support on the coin integration. I've tested your code and it works well till the signTransaction. Screen Shot 2022-03-09 at 11 43 35 AM

Hi, @skchang0710, did you reveal source account first? Any manager operation (including transaction operation) can be submitted before revealing the public key of the account by sending reveal operation.

**Comment by skchang0710** [comment]
The other effort should be done before this PR approved, It is about the SDK convention - We don't apply internet request in this SDK to avoid exclusive methods on different platform.

So the recommendation is moving the "isRevealNeeded" method from coin-xtz to coin-tester.
Screen Shot 2022-03-09 at 11 50 49 AM

**Comment by skchang0710** [comment]
> > Hi @ellingtonsu, thank you for your support on the coin integration. I've tested your code and it works well till the signTransaction. Screen Shot 2022-03-09 at 11 43 35 AM
> 
> Hi, @skchang0710, did you reveal source account first? Any manager operation (including transaction operation) can be submitted before revealing the public key of the account by sending reveal operation.

Yes, it is my mistake. I try to generate the other address to copy but forgot to set it back to the revealed one.
It passed now, I will test the other methods, thank you.

**Comment by skchang0710** [comment]
> > > Hi @ellingtonsu, thank you for your support on the coin integration. I've tested your code and it works well till the signTransaction. Screen Shot 2022-03-09 at 11 43 35 AM
> > 
> > 
> > Hi, @skchang0710, did you reveal source account first? Any manager operation (including transaction operation) can be submitted before revealing the public key of the account by sending reveal operation.
> 
> Yes, it is my mistake. I try to generate the other address to copy but forgot to set it back to the revealed one. It passed now, I will test the other methods, thank you.

**Comment by skchang0710** [comment]
All operations have been signed and sent on chain properly.
There are only three arguments need to be clarified.

1. fee : The fee calculation should be demonstrated in the code, either in "coin-sdk" or in "coin-tester".
2. gas_limit : What is it and where is it from. (API ?)
3. storage_limit : What is it and where is it from. (API ?)

**Comment by ellingtonsu** [comment]
> The other effort should be done before this PR approved, It is about the SDK convention - We don't apply internet request in this SDK to avoid exclusive methods on different platform.
> 
> So the recommendation is moving the "isRevealNeeded" method from coin-xtz to coin-tester. Screen Shot 2022-03-09 at 11 50 49 AM

OK. The "isRevealNeed" method has been moved from coin-xtz to coin-tester in commit [4b53f3e](https://github.com/CoolBitX-Technology/coolwallet-sdk/pull/288/commits/4b53f3ed54eab133affd0df030a597be7b33aa63)

**Comment by ellingtonsu** [comment]
> All operations have been signed and sent on chain properly. There are only three arguments need to be clarified.
> 
> 1. fee : The fee calculation should be demonstrated in the code, either in "coin-sdk" or in "coin-tester".
> 2. gas_limit : What is it and where is it from. (API ?)
> 3. storage_limit : What is it and where is it from. (API ?)

The description of fee, gas_limit, and storage_limit is introduced in [chain documentation (Section 1.3 and Section 5.4)](https://docs.google.com/document/d/1xF-1mYRnWzdRCknBpCSIFOXKfGLjJJYKtjtpbgShdiA/edit?usp=sharing).

The estimate has been implemented in commit 699d1d3.

**Comment by skchang0710** [comment]
Since the XTZ SDK works as the transaction generated by it can be sent on chain successfully. The remaining confusion is how to fetch reasonable fees and other default values. Please add descriptions or demonstrate it in the coin-tester.

**Comment by ellingtonsu** [comment]
> Since the XTZ SDK works as the transaction generated by it can be sent on chain successfully. The remaining confusion is how to fetch reasonable fees and other default values. Please add descriptions or demonstrate it in the coin-tester.

In taquito 12.0.0, it is possible to estimate with configured wallet and does not require the private key except for reveal operation. It is safe to use default estimate for reveal operation that is immutable with fixed cost. A mockCoolWallet can be and has been implemented in coin-tester for dry-run estmation in commit 8343ef9.

**Review by skchang0710 — APPROVED** [review]

**Review by hank121314 — APPROVED** [review]

**Review by srt1678 — APPROVED** [review]

**Pull request merged**
